FROM centos:centos7
MAINTAINER D. J. Hagberg <dhagberg@millibits.com>
#ENV ksurl http://puppetmaster:4080/ks-dev
ENV BUILDTS @BUILDTS@
COPY build/ /root/build/
RUN /root/build/post_install $BUILDTS

CMD ["/usr/bin/bash"]
